name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{ vars.BASE_URL}}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Read Environment Variables
        run: echo "My BASE_URL value is ${{ vars.BASE_URL}}"

      - name: Run tests
        run: npx playwright test
        continue-on-error: true

      - name: Checkout gh-pages branch
        if: always()
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
        continue-on-error: true

      - name: Copy Allure history
        if: always()
        run: |
          if [ -d gh-pages/history ]; then
            mkdir -p allure-results/history
            cp -r gh-pages/history/* allure-results/history/
          fi

      - name: Generate Allure report
        if: always()
        run: npx allure generate

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report